version: '3.9'

networks:
  invia-net:

volumes:
  invia-db:

services:
  invia-jaeger:
    image: jaegertracing/all-in-one:1.61.0
    container_name: invia-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - invia-net
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  invia-db:
    build:
      context: ./deploy
      dockerfile: db.Dockerfile
    container_name: invia-db
    user: root  # needed because windows hates me
    volumes:
      - invia-db:/var/lib/postgresql/data
    networks:
      - invia-net
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  invia-users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invia-users
    networks:
      - invia-net
    ports:
      - "8087:8087"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - invia-db
    environment:
      - INVIA_CONFIG_PATH=config/prod.yaml
