env: "local"
version: "1.0.0"
db_connect: "host=localhost port=25432 dbname=postgres user=postgres password=postgres client_encoding=UTF8 sslmode=disable"
port: 8087
use_tracing: true
tracing_address: "http://localhost:14268/api/traces"
